### ISSUE TITLE
Compiler produces wrong output

### ISSUE THREAD

**Issue by Inky-developer** [TheCymaera/emcl#1]
Using the following input, the compiler produces a wrong output:
```
score gol "neighbours" = score gol "whatever";
score gol "neighbours" += 15;
```

It seems like the optimizer deletes a bit too much, as the resulting file just contains:
```
scoreboard players add neighbours gol 15
```

**Comment by TheCymaera** [comment]
Fixed. Optimizer incorrectly assumed it could reduce this pattern:
a op b
a = a
To:
a = a
