### ISSUE TITLE
Variables not being initialized?

### ISSUE THREAD

**Issue by Goldenlion5648** [TheCymaera/emcl#1]
When running the simple example given on the site
```
for (int i = 0; i < 10; i += 1) {
	/tellraw @a "Hello World!"
}
// This is just like the previous example, except all 
// the loop-logic is written on a single line.
```
It only prints "Hello World!" once. From what it looks like, there is no mcfunction file where the scoreboard for the variable i is initialized. Am I missing something?

**Comment by TheCymaera** [comment]
There is an init function. You can make it run automatically by pasting the namespaced-id in the `onLoad` field inside the `emcl.config.json` file.

Source:
![Screenshot 2023-02-07 at 1 31 25 AM](https://user-images.githubusercontent.com/69355340/217043245-bf18315a-a9ed-4d59-89a4-ae55e0b82bdf.png)

Optimized IR:
![Screenshot 2023-02-07 at 1 31 17 AM](https://user-images.githubusercontent.com/69355340/217043254-40ce4338-df2b-47a4-8a6f-c84504eaa884.png)

**Comment by TheCymaera** [comment]
I should probably clarify this in the documentation.

**Comment by Goldenlion5648** [comment]
[functions.zip](https://github.com/TheCymaera/emcl/files/10667664/functions.zip)
This is what was generated, where is the scoreboard made?

**Comment by TheCymaera** [comment]
Oh, my bad. Should be fixed now.
